events {}

http {
    server {
        listen 80; # 외부에서 들어오는 80번(기본 HTTP) 포트 트래픽을 받습니다.

        location / {
            # 들어온 요청을 내부망에 있는 'monitor-app' 컨테이너의 8080 포트로 토스합니다.
            proxy_pass http://monitor-app:8080;
        }
    }
}