events {}

http {
    server {
        listen 80; # 외부에서 들어오는 80번(기본 HTTP) 포트 트래픽을 받습니다.

        # 사용자가 기본 주소(/)로 접속하면 화면(HTML)을 보여준다.
        location / {
            root /user/share/nginx/html;
            index index.html;
        }

        # 화면 안의 자바스크립트가 /api/status 로 데이터를 요청하면, 모니터링 서버(8080)로 넘겨준다.
        location /api/ {
            proxy_pass http://monitor-app:8080;
        }
    }
}